repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - args:
    - --fix
    id: ruff
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.9
- hooks:
  - id: poetry-check
  - id: poetry-lock
  - id: poetry-install
  repo: https://github.com/python-poetry/poetry
  rev: 1.7.0
- hooks:
  - entry: poetry run pytest -n auto --random-order
    id: pytest-check
    language: system
    name: pytest-check
    pass_filenames: false
    types_or:
    - html
    - python
  - entry: ./checkcoverage.sh
    id: coverage-check
    language: system
    name: coverage-check
    pass_filenames: false
    types_or:
    - html
    - python
  repo: local
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
